//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Journal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gr691_fnvEntities : DbContext
    {
        public gr691_fnvEntities()
            : base("name=gr691_fnvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Instructed> Instructeds { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<OSJ> OSJs { get; set; }
        public virtual DbSet<Passage> Passages { get; set; }
        public virtual DbSet<ViewInstruct> ViewInstructs { get; set; }
        public virtual DbSet<Violation> Violations { get; set; }
    }
}
