//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Journal
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSJ
    {
        public int Номер_инструктажа { get; set; }
        public string Название_инструктажа { get; set; }
        public Nullable<int> Номер_инструктурируемого { get; set; }
        public Nullable<int> Номер_инструктора { get; set; }
        public Nullable<int> Номер_прохождения { get; set; }
        public Nullable<int> Номер_нарушения { get; set; }
        public int Номер_вида_инструктажа { get; set; }
    
        public virtual Instructed Instructed { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Violation Violation { get; set; }
        public virtual Passage Passage { get; set; }
        public virtual ViewInstruct ViewInstruct { get; set; }
    }
}
